### ISSUE TITLE
目前实行到什么地步了？

### ISSUE THREAD

**Issue by i5ting** [trekjs/route-mapper#8]

**Comment by fundon** [comment]
@i5ting 目前在 **dev** 分支，https://github.com/trekjs/route-mapper/blob/dev/test/RouteMapper.test.js 这个文件里面的测试都支持，可以执行 `$ DEBUG=route-mapper* npm test` 进行查看，还有这个生成的嵌套路由，跟 rails 生成的意志 (`$ rails new blog; cat config/routes.rb`)
