### ISSUE TITLE
是否可以去掉对 babel 的依赖

### ISSUE THREAD

**Issue by luin** [trekjs/route-mapper#9]
现在 RouteMapper#draw 会依赖 babel（https://github.com/trekjs/route-mapper/blob/master/src/RouteMapper.js#L638），而 package.json 中没有包含 babel，导致运行出错。看了下其他地方没有使用到 draw 方法，是不是可以去掉？

**Comment by fundon** [comment]
囧，这个没主意到

`draw()` ，更加简洁的调用方式，为了支持 `ES6+` 语法，使用了 `babel` tranformer，看这里
https://github.com/trekjs/route-mapper/blob/master/test/draw.test.js
https://github.com/trekjs/route-mapper/blob/master/test/fixtures/routes.js

我先把 `babel` 放到 `dependencies` 中

**Comment by fundon** [comment]
Bumped v0.4.4
